#!/bin/bash==============================================================================Script Name : clone.shDescription : Mengkloning/Migrasi VPS Ubuntu (Sumber) ke VPS Ubuntu (Tujuan)Author      : AI SysAdmin==============================================================================Warna untuk output terminalRED='\033[0;31m'GREEN='\033[0;32m'YELLOW='\033[1;33m'NC='\033[0m' # No Colorecho -e "${GREEN}=======================================${NC}"echo -e "${GREEN}    VPS Migration Script (Rsync)       ${NC}"
echo -e "${GREEN}=======================================${NC}"Pastikan script dijalankan sebagai rootif [ "$EUID" -ne 0 ]; then
echo -e "${RED}[ERROR] Script ini harus dijalankan sebagai root (gunakan sudo).${NC}"exit 1fi==============================================================================1. Pengecekan Prasyarat (Rsync & sshpass)==============================================================================echo -e "${YELLOW}[INFO] Memeriksa prasyarat (rsync, sshpass)...${NC}"if ! command -v rsync &> /dev/null || ! command -v sshpass &> /dev/null; thenecho -e "${YELLOW}[INFO] Menginstal paket yang dibutuhkan...${NC}"apt-get update -y > /dev/null 2>&1apt-get install rsync sshpass -y > /dev/null 2>&1echo -e "${GREEN}[OK] Paket rsync dan sshpass berhasil diinstal.${NC}"elseecho -e "${GREEN}[OK] Prasyarat sudah terpenuhi.${NC}"fi==============================================================================2. Input Interaktif (Target & Kredensial)==============================================================================echo ""read -p "Masukkan IP Address VPS Sumber: " SOURCE_IPif [ -z "$SOURCE_IP" ]; then
echo -e "${RED}[ERROR] IP Address tidak boleh kosong.${NC}"exit 1fiMeminta password dengan masking (-s)read -s -p "Masukkan Password root VPS Sumber: " SOURCE_PASSecho ""if [ -z "$SOURCE_PASS" ]; then
echo -e "${RED}[ERROR] Password tidak boleh kosong.${NC}"exit 1fi==============================================================================3. Konfigurasi Rsync & Exclusions==============================================================================Daftar direktori dan file yang HARUS dikecualikan agar VPS baru tidak rusakEXCLUDE_ARGS=(--exclude={"/boot/","/dev/","/proc/","/sys/","/tmp/","/run/","/mnt/","/media/","/lost+found"}--exclude="/etc/fstab"--exclude="/etc/mtab"--exclude="/etc/resolv.conf"--exclude="/etc/network/interfaces*"      # Jika menggunakan ifupdown--exclude="/etc/netplan/"              # Jika menggunakan netplan (Ubuntu modern)
--exclude="/etc/networkd-dispatcher/"--exclude="/etc/udev/rules.d/70-persistent-net.rules"--exclude="/etc/hostname"--exclude="/etc/hosts"--exclude="/var/lib/dhcp/"
--exclude="/var/run/"--exclude="/var/lock/"
--exclude="/root/.ssh/"                # Opsional: Cegah menimpa kunci SSH tujuan)echo -e "\n${YELLOW}[INFO] Memulai proses sinkronisasi dari $SOURCE_IP...${NC}"echo -e "${YELLOW}[INFO] Proses ini mungkin memakan waktu lama tergantung ukuran data.${NC}"Opsi Rsync:-a : Archive mode (mempertahankan permissions, ownership, symlinks, dll)-v : Verbose (menampilkan file yang sedang diproses)-P : Menampilkan progress bar dan mengizinkan resume-x : Jangan lewati batas filesystem (opsional, tergantung setup partisi)--numeric-ids : Penting agar UID/GID tidak kacau antar server-e "ssh ..." : Perintah SSH dengan opsi agar tidak prompt fingerprintexport SSHPASS="$SOURCE_PASS"Jalankan Rsync dengan sshpasssshpass -e rsync -avP --numeric-ids -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" "${EXCLUDE_ARGS[@]}" root@$SOURCE_IP:/ /RSYNC_EXIT_CODE=$?Hapus variabel password dari memori environment secepatnyaunset SSHPASSunset SOURCE_PASS==============================================================================4. Hasil Eksekusi==============================================================================echo -e "\n======================================="if [ $RSYNC_EXIT_CODE -eq 0 ]; then
echo -e "${GREEN}[SUCCESS] Sinkronisasi data selesai tanpa error!${NC}"
echo -e "${YELLOW}[WARNING] Disarankan untuk me-reboot VPS ini agar perubahan sistem berlaku sepenuhnya.${NC}"
else
echo -e "${RED}[ERROR] Rsync selesai dengan kode keluar: $RSYNC_EXIT_CODE.${NC}"echo -e "${RED}Mungkin terjadi error (seperti file yang sedang terbuka atau putus koneksi). Silakan periksa log.${NC}"fiecho -e "=======================================\n"
